using System.Text;

namespace Firepit.Knowledge.Indexing;

// Compiles the always-on tier: every knowledge doc with `pin: true`
// frontmatter is concatenated into `{project}/.firepit/knowledge-pinned.md`.
// The seed CLAUDE.md convention imports that file (`@.firepit/knowledge-pinned.md`),
// so pinned docs are PUSHED into the agent's context at session start with
// zero tool calls — the push tier next to the searchable pull tier.
//
// The digest lives one level ABOVE the knowledge dir so it never indexes
// itself, and it is committed (deterministic, derived from committed docs) so
// a fresh clone pushes memory before Firepit ever runs.
internal static class PinnedDigest
{
    public const string FileName = "knowledge-pinned.md";

    // Context budget: the pinned tier is the reflex core, not the library.
    internal const int MaxDocs = 10;
    internal const int MaxChars = 12_000;

    /// <summary>
    /// Regenerates the digest at <paramref name="digestPath"/> from the
    /// `pin: true` docs under <paramref name="knowledgeDir"/>. Inert when the
    /// scope never opted into knowledge (no dir, no digest). Returns true when
    /// the file on disk changed.
    /// </summary>
    public static bool Regenerate(string knowledgeDir, string digestPath)
    {
        var dirExists = Directory.Exists(knowledgeDir);
        if (!dirExists && !File.Exists(digestPath))
        {
            return false;
        }

        var pinned = new List<(string Rel, string Body)>();
        if (dirExists)
        {
            foreach (var file in Directory
                .EnumerateFiles(knowledgeDir, "*.md", SearchOption.AllDirectories)
                .OrderBy(f => f, StringComparer.OrdinalIgnoreCase))
            {
                string text;
                try
                {
                    text = File.ReadAllText(file);
                }
                catch (IOException)
                {
                    continue;
                }

                if (!PinnedFrontmatter.IsPinned(text))
                {
                    continue;
                }

                var rel = Path.GetRelativePath(knowledgeDir, file).Replace('\\', '/');
                pinned.Add((rel, PinnedFrontmatter.StripFrontmatterBlock(text).Trim()));
            }
        }

        var content = Compose(pinned);
        string? existing = null;
        if (File.Exists(digestPath))
        {
            try
            {
                existing = File.ReadAllText(digestPath);
            }
            catch (IOException)
            {
            }
        }

        if (existing == content)
        {
            return false;
        }

        Directory.CreateDirectory(Path.GetDirectoryName(digestPath)!);
        File.WriteAllText(digestPath, content);
        return true;
    }

    private static string Compose(IReadOnlyList<(string Rel, string Body)> pinned)
    {
        var sb = new StringBuilder();
        sb.Append(
            "<!-- Generated by Firepit from `pin: true` docs in .firepit/knowledge/. " +
            "Do not edit — edit the pinned docs instead. -->\n\n");
        sb.Append("# Pinned knowledge\n\n");

        if (pinned.Count == 0)
        {
            // Keep this in sync with FirepitBlueprintDefaults.PinnedDigestSeed
            // (Firepit.Core) — drift is harmless (one extra rewrite on the
            // next index pass) but noisy in git.
            sb.Append(
                "No pinned documents yet. Add `pin: true` to a knowledge doc's " +
                "frontmatter (or pass pinned=true to firepit_knowledge_add) to " +
                "auto-load it here.\n");
            return sb.ToString();
        }

        var included = 0;
        var chars = 0;
        var skipped = new List<string>();
        foreach (var (rel, body) in pinned)
        {
            if (included >= MaxDocs || chars + body.Length > MaxChars)
            {
                skipped.Add(rel);
                continue;
            }

            sb.Append("<!-- pinned: ").Append(rel).Append(" -->\n\n");
            sb.Append(body).Append("\n\n");
            included++;
            chars += body.Length;
        }

        if (skipped.Count > 0)
        {
            sb.Append(
                "Over the pinned budget — not inlined (unpin something, or " +
                "fetch these via firepit_knowledge_get): ");
            sb.Append(string.Join(", ", skipped)).Append('\n');
        }

        return sb.ToString();
    }
}
